AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-facebook-webhooks

Transform:
- AWS::Serverless-2016-10-31

Resources:
  createSubscription:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/index.get
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
