AWSTemplateFormatVersion: 2010-09-09
Description: >-
  facebook-webhooks-sns

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        TOPIC_LEADGEN: !Ref TopicLeadgen

Resources:
  TopicLeadgen:
    Type: AWS::SNS::Topic
  doGet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/index.get
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Events:
        Get:
          Type: Api
          Properties:
            Path: /
            Method: GET
  doPost:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/index.post
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Events:
        Get:
          Type: Api
          Properties:
            Path: /
            Method: POST
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt TopicLeadgen.TopicName

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
